services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: localhost # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
     image: mysql:8.0
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_USER: pyro
       MYSQL_PASSWORD: cynical
       MYSQL_DATABASE: slop
     ports:
       - "3306:3306"
     volumes:
        # Where our data will be persisted
        - my-db:/var/lib/mysql
  # Defines a named volume
volumes:
  my-db: