openapi: 3.0.3
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: oabdelsalam@my.bcit.ca
paths:
  /stats:
    get:
      summary: gets new temperature readings
      operationId: app.get_stats
      description: Gets Temperature and Precipitation statistics
      responses:
        '200':
          description: Successfully returned a stats object
          content:
            application/json:
              schema:
                type: object
                items:
                $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    ReadingStats:
      required:
      - num_temp_readings
      - min_temp_celcius
      - max_temp_celcius
      - num_precip_readings
      - max_precip_mm
      properties:
        num_temp_readings:
          type: integer
          example: 500000
        min_temp_celcius:
          type: integer
          example: -60
        max_temp_celcius:
          type: integer
          example: 60
      type: object