openapi: 3.0.3
info:
  description: This API receives motion detection readings in form of pictures & recives temperature readings at the time of the detection
  version: "1.0.0"
  title: Motion & Temperature API
  contact:
    email: oabdelsalam@my.bcit.ca
paths:
  /motiontemp/temperature:
    post:
      summary: Reports a batch of temperature sensor readings
      operationId: app.report_temperature_readings
      description: Adds a batch of temperature readings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemperatureReading'
      responses:
        '201':
          description: batch successfully received
        '400':
          description: 'invalid input, object invalid'
    
  /motiontemp/motion:
    post:
      summary: Reports a batch of motion sensor readings
      operationId: app.report_motion_readings
      description: Adds a batch of motion readings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MotionReading'
      responses:
        '201':
          description: batch successfully received
        '400':
          description: 'invalid input, object invalid'

components:
  schemas:
    TemperatureReading:
      required:
        - station_id
        - station_name
        - temperature_celsius
        - reporting_timestamp
        - recorded_timestamp
        - trace_id
      properties:
        station_id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        station_name:
          type: string
          example: "Yellowknife North"
        temperature_celsius:
          type: number
          example: -13.2
        reporting_timestamp:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        recorded_timestamp:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
      type: object


      
    MotionReading:
      required:
      - station_id
      - station_name
      - station_location
      - batch_timestamp
      - picture
      - animal_speed
      - recorded_timestamp
      - trace_id
      properties:
        station_id:
          type: string
          format: uuid
          example: "dc73bb90-ee3c-4a7b-b151-d09edbde4e32"
        station_name:
          type: string
          example: "Churchill River Upland Ecoregion"
        station_location:
          type: string
          description: GPS location in degrees-minutes-seconds (DMS) format
          example: "45° 46' 52\" N 108° 30' 14\" W"
        batch_timestamp:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"     
        picture:
          type: string
          example: motion-detected-1-33.jpg
        animal_speed:
          type: integer
          description: units m/s
          example: 4
        recorded_timestamp:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        trace_id:
          type: integer
          example: 1674123456789012345
      type: object