server {
    listen 80;

    location /health {
        proxy_pass http://health-check:8120;
    }
    
    location /storage {
   	 proxy_pass http://storage:8090;
    }

    # Receiver service
    location /receiver {
        proxy_pass http://receiver:8010;
    }

    # Analyzer service
    location /analyzer {
        proxy_pass http://analyzer:8025;
    }

    location /processing {
        proxy_pass http://processing:8100;
    }
    # Dashboard (static frontend)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}
